#!/sbin/openrc-run
# Distributed under the terms of the GNU General Public License v2

extra_commands="reload"

pidfile=/run/${SVCNAME}.pid
command="/usr/bin/${SVCNAME}"
command_args="aggr"

data_dir=${data_dir:-"/var/lib/${SVCNAME}"}

depend() {
	need net
	use  dns logger
}

start_pre() {
	checkpath --directory --owner bolo:bolo --mode 0770 \
		${data_dir}
}

reload() {
	ebegin "Reloading Bolo"
	start-stop-daemon --exec ${command} --signal HUP \
		--pidfile ${PIDFILE}
	eend $?
}

# vim:ts=4
