#!/sbin/openrc-run
# Distributed under the terms of the GNU General Public License v2

pidfile=${pidfile:-"/run/${SVCNAME}.pid"}
user=${user:-"root"}
group=${group:-"root"}
ENDPOINT=${ENDPOINT:-"tcp://127.0.0.1:2999"}

command="/usr/sbin/${SVCNAME}"
command_args="-u ${user} -g ${group} -e ${ENDPOINT} -s ${SPLAY} -c ${COMMANDS} -p ${pidfile}"
start_stop_daemon_args="--user ${user} --group ${group}"

depend() {
	need net
	use  dns logger
}
