# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI=5

MODULE_AUTHOR="YANICK"

inherit perl-module

DESCRIPTION="Encrypted cookie-based session backend for Dancer"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64 amd64-fbsd x86 x86-fbsd x86-freebsd x64-freebsd amd64-linux x86-linux"
IUSE="test"

RDEPEND="
	dev-perl/Dancer
	dev-perl/Time-Duration-Parse
	>=dev-perl/Session-Storage-Secure-0.007
	dev-perl/string-crc32
	dev-perl/HTTP-Cookies
	dev-perl/Crypt-Rijndael
	dev-perl/HTTP-Date
	dev-perl/crypt-cbc
	test? (
		dev-perl/Test-Exception
		dev-perl/Test-NoWarnings
		dev-perl/Test-TCP
	)
"
DEPEND="${RDEPEND}"
