# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="DAGOLDEN"


inherit perl-module

DESCRIPTION="Encrypted cookie-based session backend for Dancer"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="alpha amd64 amd64-fbsd arm arm64 hppa ia64 m68k mips ppc ppc64 s390 sh sparc sparc-fbsd x86 x86-fbsd   ppc-aix x86-freebsd x64-freebsd sparc64-freebsd hppa-hpux ia64-hpux x86-interix amd64-linux arm-linux ia64-linux ppc64-linux x86-linux ppc-macos x86-macos x64-macos m68k-mint x86-netbsd ppc-openbsd x86-openbsd x64-openbsd sparc-solaris sparc64-solaris x64-solaris x86-solaris x86-winnt x86-cygwin"
IUSE=""

DEPEND="dev-perl/Dancer
	dev-perl/Test-NoWarnings
	dev-perl/Test-TCP
	dev-perl/Time-Duration-Parse
	dev-perl/Test-Exception
	>=dev-perl/Session-Storage-Secure-0.007
	dev-perl/string-crc32
	dev-perl/HTTP-Cookies
	dev-perl/Crypt-Rijndael
	dev-perl/HTTP-Date
	dev-perl/crypt-cbc
	dev-lang/perl"
